"use client";
import { useEffect, useState, useCallback } from "react";
import { Card } from "@/components/ui/Card";
import { Button, Input, Textarea, Select } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { formatDate, todayISO, getDaysSince } from "@/lib/utils";
import { TrendingUp, Plus, Trash2, Flame, Star, Trophy, BookOpen, Dumbbell, Target, Zap } from "lucide-react";

interface TimelineEvent {
  id: number;
  date: string;
  title: string;
  description?: string | null;
  category?: string | null;
  isAutoGenerated: boolean;
}

const CATEGORIES = ["Milestone", "Study", "Fitness", "Health", "Personal", "Career", "Other"];

const categoryIcon = (cat?: string | null) => {
  switch (cat) {
    case "Study": return BookOpen;
    case "Fitness": return Dumbbell;
    case "Health": return Star;
    case "Milestone": return Trophy;
    case "Career": return Target;
    default: return Flame;
  }
};

const categoryColor = (cat?: string | null) => {
  switch (cat) {
    case "Study": return "text-indigo-400 bg-indigo-500/10 border-indigo-500/20";
    case "Fitness": return "text-green-400 bg-green-500/10 border-green-500/20";
    case "Health": return "text-pink-400 bg-pink-500/10 border-pink-500/20";
    case "Milestone": return "text-amber-400 bg-amber-500/10 border-amber-500/20";
    case "Career": return "text-orange-400 bg-orange-500/10 border-orange-500/20";
    default: return "text-purple-400 bg-purple-500/10 border-purple-500/20";
  }
};

export default function TimelinePage() {
  const [events, setEvents] = useState<TimelineEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [addOpen, setAddOpen] = useState(false);
  const [form, setForm] = useState({
    date: todayISO(),
    title: "",
    description: "",
    category: "Milestone",
  });

  const [comebackStart, setComebackStart] = useState(todayISO());

  const fetchEvents = useCallback(async () => {
    setLoading(true);
    try {
      const [eventsData, settingsData] = await Promise.all([
        fetch("/api/timeline").then((r) => r.json()),
        fetch("/api/settings").then((r) => r.json()),
      ]);
      setEvents(Array.isArray(eventsData) ? eventsData : []);
      if (settingsData?.comebackStartDate) setComebackStart(settingsData.comebackStartDate);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchEvents(); }, [fetchEvents]);

  const addEvent = async () => {
    if (!form.title) return;
    await fetch("/api/timeline", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...form, isAutoGenerated: false }),
    });
    setForm({ date: todayISO(), title: "", description: "", category: "Milestone" });
    setAddOpen(false);
    fetchEvents();
  };

  const deleteEvent = async (id: number) => {
    if (!confirm("Delete this milestone?")) return;
    await fetch(`/api/timeline?id=${id}`, { method: "DELETE" });
    fetchEvents();
  };

  const dayNumber = getDaysSince(comebackStart);

  // Group events by month
  const groupedEvents = events.reduce<Record<string, TimelineEvent[]>>((acc, e) => {
    const month = e.date.slice(0, 7);
    (acc[month] = acc[month] || []).push(e);
    return acc;
  }, {});

  const sortedMonths = Object.keys(groupedEvents).sort((a, b) => b.localeCompare(a));

  return (
    <div className="p-6 max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <TrendingUp className="text-indigo-400" size={22} />
            <h1 className="text-2xl font-bold text-white">My Comeback</h1>
          </div>
          <p className="text-white/30 text-sm">Your transformation, chronologically</p>
        </div>
        <Button onClick={() => setAddOpen(true)}><Plus size={16} /> Add Milestone</Button>
      </div>

      {/* Hero Banner */}
      <div className="relative bg-gradient-to-br from-indigo-900/40 to-purple-900/20 border border-indigo-500/20 rounded-2xl p-6 overflow-hidden">
        <div className="absolute top-0 right-0 text-[120px] font-black text-white/3 select-none leading-none">{dayNumber}</div>
        <div className="relative">
          <p className="text-indigo-400/70 text-xs uppercase tracking-widest mb-2">The Comeback</p>
          <div className="flex items-baseline gap-3">
            <span className="text-5xl font-black text-white">Day {dayNumber}</span>
          </div>
          <p className="text-white/40 text-sm mt-2">Since {formatDate(comebackStart)}</p>
          <p className="text-white/20 text-xs mt-4 italic">"The comeback is always greater than the setback."</p>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-12 text-white/20">Loading...</div>
      ) : events.length === 0 ? (
        <Card className="text-center py-12">
          <TrendingUp className="mx-auto mb-3 text-white/10" size={40} />
          <p className="text-white/30 mb-2">No milestones recorded yet</p>
          <p className="text-white/15 text-sm mb-4">Start logging your wins and achievements</p>
          <Button onClick={() => setAddOpen(true)}><Plus size={14} /> Add First Milestone</Button>
        </Card>
      ) : (
        <div className="space-y-8">
          {sortedMonths.map((month) => {
            const monthDate = new Date(month + "-01");
            const monthLabel = monthDate.toLocaleDateString("en-IN", { month: "long", year: "numeric" });
            const monthEvents = groupedEvents[month].sort((a, b) => b.date.localeCompare(a.date));

            return (
              <div key={month}>
                <h3 className="text-xs text-white/25 uppercase tracking-widest mb-4">{monthLabel}</h3>
                <div className="relative">
                  {/* Timeline line */}
                  <div className="absolute left-4 top-0 bottom-0 w-px bg-white/5" />
                  <div className="space-y-4">
                    {monthEvents.map((event, idx) => {
                      const Icon = categoryIcon(event.category);
                      const colorClass = categoryColor(event.category);
                      const daysIn = getDaysSince(comebackStart) - Math.max(0, Math.floor((new Date(todayISO()).getTime() - new Date(event.date).getTime()) / 86400000));
                      return (
                        <div key={event.id} className="flex gap-4">
                          {/* Dot */}
                          <div className={`relative z-10 w-8 h-8 rounded-full border flex items-center justify-center shrink-0 ${colorClass}`}>
                            <Icon size={14} />
                          </div>
                          <div className="flex-1 pb-4">
                            <div className="flex items-start justify-between">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-1">
                                  <p className="text-sm font-semibold text-white">{event.title}</p>
                                  {event.category && (
                                    <span className={`text-xs px-2 py-0.5 rounded-full border ${colorClass}`}>{event.category}</span>
                                  )}
                                </div>
                                <p className="text-xs text-white/30">{formatDate(event.date)}</p>
                                {event.description && (
                                  <p className="text-sm text-white/50 mt-1">{event.description}</p>
                                )}
                              </div>
                              {!event.isAutoGenerated && (
                                <button onClick={() => deleteEvent(event.id)} className="text-white/10 hover:text-red-400 p-1 ml-2">
                                  <Trash2 size={13} />
                                </button>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      <Modal isOpen={addOpen} onClose={() => setAddOpen(false)} title="Add Milestone">
        <div className="space-y-4">
          <Input label="Date" type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
          <Input label="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Completed DBMS, New PR on Bench Press" />
          <Textarea label="Description (optional)" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={2} />
          <Select label="Category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} options={CATEGORIES.map((c) => ({ value: c, label: c }))} />
          <div className="flex gap-3">
            <Button onClick={addEvent} className="flex-1">Add Milestone</Button>
            <Button variant="secondary" onClick={() => setAddOpen(false)}>Cancel</Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
